### ISSUE TITLE
Please add a link back to the blog post

### ISSUE THREAD

**Issue by Rio517** [leanpanda-com/liveview-authorisation#1]
I was googling around for the blog post, but couldn't find it. I stumbled acorss this repo just poking around to find OS projects that might use liveview. 

Thanks for sharing!

-Mario

**Comment by joaobalsini** [comment]
Hey Mario, the article was still in review.

But here it is, it was published today:
https://www.leanpanda.com/blog/authentication-and-authorisation-in-phoenix-liveview/

Thanks for the interest :)

Best regards,
João Gilberto

**Comment by joaobalsini** [comment]
The link was added to the readme :)
